[2025-05-14T12:00:03.057+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-14T12:00:03.084+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-14T11:00:00+00:00 [queued]>
[2025-05-14T12:00:03.091+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-14T11:00:00+00:00 [queued]>
[2025-05-14T12:00:03.092+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-14T12:00:03.109+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): check_if_retrain_needed> on 2025-05-14 11:00:00+00:00
[2025-05-14T12:00:03.117+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'check_if_retrain_needed', 'scheduled__2025-05-14T11:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmpuz7nxmcn']
[2025-05-14T12:00:03.119+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask check_if_retrain_needed
[2025-05-14T12:00:03.122+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2406) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-14T12:00:03.123+0000] {standard_task_runner.py:63} INFO - Started process 2409 to run task
[2025-05-14T12:00:03.165+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-14T11:00:00+00:00 [running]> on host 57cf39d9f769
[2025-05-14T12:00:03.260+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='check_if_retrain_needed' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T11:00:00+00:00'
[2025-05-14T12:00:03.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-14T12:00:03.279+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-14T12:00:03.291+0000] {python.py:237} INFO - Done. Returned value was: trigger_retrain
[2025-05-14T12:00:03.292+0000] {branch.py:36} INFO - Branch into trigger_retrain
[2025-05-14T12:00:03.292+0000] {skipmixin.py:178} INFO - Following branch trigger_retrain
[2025-05-14T12:00:03.307+0000] {skipmixin.py:246} INFO - Skipping tasks [('end', -1)]
[2025-05-14T12:00:03.339+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-14T12:00:03.358+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=monitor_PWU, task_id=check_if_retrain_needed, execution_date=20250514T110000, start_date=20250514T120003, end_date=20250514T120003
[2025-05-14T12:00:03.417+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-14T12:00:03.443+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-14T12:00:03.447+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
