[2025-05-11T15:51:12.709+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-11T15:51:12.741+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.monitor_model manual__2025-05-11T15:51:11.427003+00:00 [queued]>
[2025-05-11T15:51:12.750+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.monitor_model manual__2025-05-11T15:51:11.427003+00:00 [queued]>
[2025-05-11T15:51:12.751+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-11T15:51:12.766+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): monitor_model> on 2025-05-11 15:51:11.427003+00:00
[2025-05-11T15:51:12.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'monitor_model', 'manual__2025-05-11T15:51:11.427003+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmpwxjjb6x1']
[2025-05-11T15:51:12.776+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask monitor_model
[2025-05-11T15:51:12.782+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-11T15:51:12.783+0000] {standard_task_runner.py:63} INFO - Started process 305 to run task
[2025-05-11T15:51:12.830+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.monitor_model manual__2025-05-11T15:51:11.427003+00:00 [running]> on host 5f1983d14d2e
[2025-05-11T15:51:12.924+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='monitor_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T15:51:11.427003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-11T15:51:11.427003+00:00'
[2025-05-11T15:51:12.925+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-11T15:51:12.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-11T15:51:12.962+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_PWU.py", line 22, in monitor_model
    raise Exception("Flask prediction failed.")
Exception: Flask prediction failed.
[2025-05-11T15:51:12.974+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=monitor_PWU, task_id=monitor_model, execution_date=20250511T155111, start_date=20250511T155112, end_date=20250511T155112
[2025-05-11T15:51:12.984+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task monitor_model (Flask prediction failed.; 305)
[2025-05-11T15:51:12.999+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-11T15:51:13.021+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-11T15:51:13.026+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
