[2025-05-21T18:00:15.190+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-21T18:00:15.221+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-21T17:00:00+00:00 [queued]>
[2025-05-21T18:00:15.228+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-21T17:00:00+00:00 [queued]>
[2025-05-21T18:00:15.229+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-21T18:00:15.247+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): check_if_retrain_needed> on 2025-05-21 17:00:00+00:00
[2025-05-21T18:00:15.252+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monitor_PWU', 'check_if_retrain_needed', 'scheduled__2025-05-21T17:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/monitor_PWU.py', '--cfg-path', '/tmp/tmpgvw268m4']
[2025-05-21T18:00:15.255+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask check_if_retrain_needed
[2025-05-21T18:00:15.256+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=302) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-21T18:00:15.257+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2025-05-21T18:00:15.301+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_PWU.check_if_retrain_needed scheduled__2025-05-21T17:00:00+00:00 [running]> on host 20faf461a3a5
[2025-05-21T18:00:15.442+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monitor_PWU' AIRFLOW_CTX_TASK_ID='check_if_retrain_needed' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T17:00:00+00:00'
[2025-05-21T18:00:15.443+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-21T18:00:15.454+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-21T18:00:15.464+0000] {python.py:237} INFO - Done. Returned value was: trigger_retrain
[2025-05-21T18:00:15.464+0000] {branch.py:36} INFO - Branch into trigger_retrain
[2025-05-21T18:00:15.465+0000] {skipmixin.py:178} INFO - Following branch trigger_retrain
[2025-05-21T18:00:15.479+0000] {skipmixin.py:246} INFO - Skipping tasks [('end', -1)]
[2025-05-21T18:00:15.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-21T18:00:15.527+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=monitor_PWU, task_id=check_if_retrain_needed, execution_date=20250521T170000, start_date=20250521T180015, end_date=20250521T180015
[2025-05-21T18:00:15.551+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-21T18:00:15.577+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-21T18:00:15.582+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
